name: Ansible Lint & Syntax Check
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ansible
        run: |
          sudo apt-get update && sudo apt-get install -y ansible
      - name: Syntax check
        run: ansible-playbook -i inventory playbooks/hello.yml --syntax-check